In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import cv2
import numpy as np
from models import Yolov4
# from utils import get_detection_data, draw_on_image

/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [3]:
model = Yolov4(
#                 weight_path=None,
              weight_path='yolov4.weights',
               img_size=(416, 416, 3),
              )

In [4]:
model.build_model()


Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
all weights read


In [21]:
model.predict('test.jpg')

img shape:  (878, 2048, 3)
# of bboxes:  16
[[0.8561276  0.32795247 0.94106495 0.9140718 ]
 [0.01599193 0.3377814  0.0899269  0.8835432 ]
 [0.9227657  0.33275706 0.99271226 0.91612923]
 [0.28431177 0.31631097 0.35304773 0.8515452 ]
 [0.5274518  0.34385657 0.6000218  0.8688481 ]
 [0.22220518 0.30806375 0.2962498  0.86417824]
 [0.08146002 0.34572628 0.17230868 0.8715507 ]
 [0.3971997  0.35493338 0.45862305 0.8604236 ]
 [0.48829973 0.34559155 0.5503693  0.85867137]
 [0.7965188  0.32469717 0.8718947  0.8838807 ]
 [0.4485646  0.33811164 0.51380825 0.8586793 ]
 [0.34138578 0.37165952 0.4187127  0.8818322 ]
 [0.6044614  0.35380775 0.65821826 0.511834  ]
 [0.17097908 0.31786725 0.25409955 0.86287385]
 [0.7337391  0.41763285 0.74769074 0.49628142]
 [0.7472476  0.32181945 0.82381356 0.87343705]] [0.9464684  0.9064533  0.85334486 0.83398163 0.82210475 0.7799453
 0.7701864  0.751453   0.74423784 0.73626405 0.7189871  0.6774594
 0.6731772  0.6186562  0.5799232  0.51278234] [ 0.  0.  0.  0.  0.  0. 

TypeError: only integer scalar arrays can be converted to a scalar index

In [22]:
a = [1, 2, 3]
a[[0, 1]]

TypeError: list indices must be integers or slices, not list